#!/bin/bash
# ---------------------------------------------------------------------------
# OMhelp: Source Code -> Help Files: Copyright (C) 1998-2006 Bradley M. Bell
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# ---------------------------------------------------------------------------
#
# Build distribution
#
# Default values used for arguments to configure during this script.
# These defaults are development system dependent and can be changed.
VIMRUNTIME=/usr/share/vim/vim70
#
# date currently in configure.ac
AcDate=`grep "^ *AC_INIT(" configure.ac | \
	sed -e "s/.*, *\([0-9][0-9]-[0-9][0-9]-[0-9][0-9]\) *,.*/\1/"`
#
# version
#
if [ "$1" = "version" ] || [ "$1" = "all" ]
then
	#
	# Today's date in yy-mm-dd decimal digit format with leading zeros
	Today=`date +%g-%m-%d`
	#
	sed configure.ac > configure.tmp -e \
	"s/(OMhelp, [0-9][0-9]-[0-9][0-9]-[0-9][0-9],/(OMhelp, $Today,/"
	#
	diff configure.ac  configure.tmp
	mv   configure.tmp configure.ac
	#
	# change Autoconf date to today
	AcDate=$Today
	#
	sed omh/overview.omh > overview.tmp -e \
	"s/Version [0-9][0-9]-[0-9][0-9]-[0-9][0-9]/Version $Today/g"
	#
	diff omh/overview.omh overview.tmp
	mv   overview.tmp     omh/overview.omh
	#
	# configure file is out of date so remove it
	if [ -e configure ]
	then
		rm configure
	fi
	#
	if [ "$1" != "all" ]
	then
		exit
	fi
fi
#
# aclocal
#
if [ "$1" = "aclocal" ] || [ "$1" = "all" ]
then
	if [ -e configure ]
	then
		rm configure
	fi
	echo "---------------------------------------------------------"
	echo "If aclocal generates warning messages, try running ./FixAclocal"
	echo "aclocal"
	aclocal
	echo "---------------------------------------------------------"
	#
	if [ "$1" != "all" ]
	then
		exit
	fi
fi  
#
# autoheader
#
if [ "$1" = "autoheader" ] || [ "$1" = "all" ]
then
	echo "autoheader"
	autoheader
	#
	if [ "$1" != "all" ]
	then
		exit
	fi
fi
#
# automake
#
if [ "$1" = "automake" ] || [ "$1" = "all" ]
then
	if [ -e configure ]
	then
		rm configure
	fi
	#
	echo "autoconf"
	autoconf
	#
	echo "automake -add-missing"
	automake --add-missing
	#
	if [ "$1" != "all" ]
	then
		exit
	fi
fi
#
# configure
#
if [ "$1" = "configure" ] || [ "$1" = "all" ]
then
	#
	if [ -e $VIMRUNTIME/syntax ]
	then
		TMP="VIMRUNTIME=$VIMRUNTIME"
	else
		TMP=""
	fi
	echo "./configure $TMP"
	./configure $TMP 
	#
	# Fix Makefile for what appears to be a bug in gzip under cygwin
	echo "FixMakefile"
	./FixMakefile
	#
	if [ "$1" != "all" ]
	then
		exit
	fi
fi
#
# compile
#
if [ "$1" = "make" ] || [ "$1" = "all" ]
then
	# remove Doc, Dev and OMhelp/dictionay.bin becasue they are
	# created by make (see ./Makefile.am).
	if [ -e Doc ]    ; then rm -r Doc ; fi
	if [ -e Dev ]    ; then rm -r Dev ; fi
	if [ -e OMhelp/dictionary.bin ] ; then rm OMhelp/dictionary.bin ; fi
	#
	echo "make"
	make
	#
	if [ "$1" != "all" ]
	then
		exit
	fi
fi
#
# dist
if [ "$1" = "dist" ] || [ "$1" = "all" ]
then
	#
	if [ -e omhelp-$AcDate ]
	then
		echo "rm -r omhelp-$AcDate"
		rm -r omhelp-$AcDate
	fi
	for file in OMhelp.dos.zip OMhelp.unix.tar.gz
	do
		if [ -e $file ]
		then
			echo "rm $file"
			rm $file
		fi
	done
	#
	echo "make dist"
	make dist
	#
	if [ ! -e omhelp-$AcDate.tar.gz ]
	then
		echo "omhelp-$AcDate.tar.gz does not exist"
		echo "perhaps version is out of date"
		#
		exit
	fi
	#
	# create the unix version
	mv omhelp-$AcDate.tar.gz OMhelp.unix.tar.gz
	#
	if [ "$1" != "all" ]
	then
		exit
	fi
fi
if [ "$1" = "dos" ] || ( [ "$1" = "all" ] && [ "$2" != "unix" ] )
then
	if [ ! -e src/src.exe ]
	then
		echo "Must use MS project to build src.exe before executing"
		echo "Build dos"
		exit 1  # error code
	fi
	if [ ! -e OMhelp.unix.tar.gz ]
	then
		echo "Must build unix version before executing: Build dos"
		exit
	fi
	#
	if [ -e omhelp-$AcDate ]
	then
		echo "rm -r omhelp-$AcDate"
		rm -r omhelp-$AcDate
	fi
	if [ -e OMhelp.dos.zip ]
	then
		echo "rm OMhelp.dos.zip"
		rm OMhelp.dos.zip
	fi
	#
	# extract from compressed tar
	tar -xvzf OMhelp.unix.tar.gz 
	#
	if [ ! -e omhelp-$AcDate ]
	then
		echo "omhelp-$AcDate.tar.gz does not exist"
		echo "perhaps OMhelp.unix.tar.gz is out of date"
		#
		exit
	fi
	#
	# convert files to dos format
	for file in  omhelp-$AcDate/*
	do
		if [ -f $file ]
		then
			unix2dos $file
		fi
	done
	for file in omhelp-$AcDate/OMhelp/*.wrd omhelp-$AcDate/OMhelp/*.xsl
	do
		if [ -f $file ]
		then
			unix2dos $file
		fi
	done
	for dir in \
		omh/getstarted 
	do
		for file in \
			omhelp-$AcDate/$dir/*.omh \
			omhelp-$AcDate/$dir/*.dat \
			omhelp-$AcDate/$dir/*.m \
			omhelp-$AcDate/$dir/*.c \
			omhelp-$AcDate/$dir/RunAll
		do
			unix2dos $file
		done
	done
	for dir in \
		src \
		src/omh \
		omh \
		omh/latex
	do
		for file in omhelp-$AcDate/$dir/*
		do
			if [ -f $file ]
			then
				unix2dos $file
			fi
		done
	done
	#
	# copy the executable to the distribution
	cp src/src.exe omhelp-$AcDate/src/src.exe
	#
	# Make sure that dates in certain files are in certain order
	# (necessary because of unix2dos conversion above)
	touch omhelp-$AcDate/aclocal.m4
	sleep 2
	touch omhelp-$AcDate/src/config.h.in
	sleep 2
	touch omhelp-$AcDate/Makefile.in
	touch omhelp-$AcDate/*/Makefile.in
	sleep 2
	touch omhelp-$AcDate/configure
	#
	# create the dos version
	zip -r OMhelp.dos.zip omhelp-$AcDate
	#
	# clean up
	rm -r omhelp-$AcDate
	#
	if [ "$1" != "all" ]
	then
		exit
	fi
fi
if [ "$1" = "test" ] || [ "$1" = "all" ] 
then
	tar -xvzf OMhelp.unix.tar.gz
	cd omhelp-$AcDate
	./Build configure
	make
	if [ "$1" != "all" ]
	then
		exit
	fi
fi
if [ "$1" = "all" ]
then
        exit
fi
#
if [ "$1" = "" ]
then
	echo "usage: Build option (where valid options are listed below)" 
else
	echo "$1 is not a valid option (valid options are listed below)"
fi
echo "option"
echo "------"
echo "version     update configure.ac and Doc.omh version number"
echo "aclocal     create aclocal.m4 file"
echo "autoheader  create a src/config.h.in file"
echo "automake    run autoconf and automake to create configure script"
echo "configure   run configure script to create make files"
echo "make        compile omhlep and use it to build its documentaiton"
echo "dist        create the distribution files OMhelp.unix.tar.gz"
echo "dos         create the distribution files OMhelp.dos.zip"
echo "test        unpack and test unix distribution"
echo
echo "Build all: This command will execute all the options in the order above"
echo
echo "Build all unix"
echo "This command will execute all the options in the order above"
echo "with the exception that \"dos\" will be excluded."
