// BEGIN SHORT COPYRIGHT
/* -----------------------------------------------------------------------
OMhelp: Source Code -> Help Files: Copyright (C) 1998-2004 Bradley M. Bell

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
------------------------------------------------------------------------ */
// END SHORT COPYRIGHT
/*
$begin AutomaticLink$$

$mindex automatic link section$$
$section Output Pass2 Automatically Generated Links$$

$table
$bold Syntax$$
$cnext $syntax%void AutomaticLink(
	int          %navigation%  ,
	SectionInfo *%section%     )%$$
$tend

$fend 20$$

$head Description$$
Writes the automatically generated links corresponding to the
specified section to the current output file.
$pre

$$
If $italic navigation$$ is zero and this section only has one frame,
no automatic links are included.
If $italic navigation$$ is zero and this section has more than one frame, 
links are only included for this section and this frame.
$pre

$$
If $italic navigation$$ is one,
links are included to this section, this frame,
the previous and next sections in $xref/SectionReadOrder//read order/$$,
and all of the sections generated by a call to
$xref/AutomaticAppendSection/$$.

$end
*/

# include "AutomaticLink.h"

# include <assert.h>
# include <string.h>
# include <stdio.h>


# include "convert.h"
# include "automatic.h"
# include "href.h"
# include "output.h"
# include "section.h"
# include "Internal2Out.h"


void AutomaticLink(int navigation, SectionInfo *section)
{
	SectionInfo *S;
	const char *fileName = OutputName();
	int i;

	// case where there are no automatic links
	if( navigation == 0 && section->nFrame == 1 )
		return;

	// Right justify the automatic links
	OutputString("<div align='right'>");

	assert( navigation == 0 || navigation == 1);
	assert( fileName != NULL );
	if( navigation )
	{
		// Previous
		S = SectionReadPrevious(section);
		if( S == NULL )
			OutputString("previous");
		else
		{	HrefOutputPass2(S->tag, "", "false", "");
			OutputString("previous");
			HrefEnd("\n");
		}

		// Next
		ConvertOutputString("  ", 1);
		S = SectionReadNext(section);
		if( S == NULL )
			OutputString("next");
		else
		{	HrefOutputPass2(S->tag, "", "false", "");
			OutputString("next");
			HrefEnd("\n");
		}

		// automatically generated links
		i = 0;
		while( AutomaticTag(i) != NULL )
		{	const char *tag = AutomaticTag(i);
			int link        = strcmp(tag, section->tag) != 0;

			ConvertOutputString("  ", 1);
			if( link )
				HrefOutputPass2(tag, "", "false", "");
			while( *tag == '_' )
				tag++;
			OutputString(tag);
			if( link )
				HrefEnd("\n");

			i++;
		}
	}


	// Header for this links
	ConvertOutputString("  ", 1);
	OutputString("This:");
	ConvertOutputString("  ", 1);

	// standard method to link to this section
	HrefOutputPass2(section->tag, "", "false", "");
	OutputString("section");
	HrefEnd(", ");

	// explicit link to this frame
	FormatOutput("<a href=\"%s\" target=\"_top\">", fileName);
	OutputString("frame</a>");

	// end of right justification
	OutputString("</div>\n");

	if( navigation )
		FormatOutput("<hr%s", Internal2Out("SelfTerminateCmd") );

	return;
}
