/* ----------------------------------------------------------------------------
OMhelp: Language Independent Embedded Documentation
          Copyright (C) 1998-2015 Bradley M. Bell
OMhelp is distributed under the terms of the
            GNU General Public License Version 2.
---------------------------------------------------------------------------- */
/*
$begin AutomaticLink$$

$mindex automatic link section$$
$section Output Pass2 Automatically Generated Links$$

$table
$bold Syntax$$
$cnext $codei%void AutomaticLink(
	int          %navigation%  ,
	SectionInfo *%section%     )%$$
$tend

$head Description$$
Writes the automatically generated links corresponding to the
specified section to the current output file.
$pre

$$
If $icode navigation$$ is zero and this section only has one frame,
no automatic links are included.
If $icode navigation$$ is zero and this section has more than one frame,
links are only included for this section and this frame.
$pre

$$
If $icode navigation$$ is one,
links are included to this section, this frame,
and all of the sections generated by a call to
$cref AutomaticAppendSection$$
(except for the table of contents).

$end
*/

# include "AutomaticLink.h"
# include "AutoTag.h"

# include <assert.h>
# include <string.h>
# include <stdio.h>


# include "convert.h"
# include "automatic.h"
# include "href.h"
# include "output.h"
# include "section.h"
# include "Internal2Out.h"


void AutomaticLink(int navigation, SectionInfo *section)
{
	const char *fileName = OutputName();
	int i;

	// case where there are no automatic links
	if( navigation == 0 && section->nFrame == 1 )
		return;

	// Right justify the automatic links
	OutputString("<div align='right'>");

	assert( navigation == 0 || navigation == 1);
	assert( fileName != NULL );
	if( navigation )
	{
		// automatically generated links
		i = 0;
		while( AutomaticTag(i) != NULL )
		// commented this out on 2010-10-22
		// if( AutomaticTag(i) != CONTENTS_TAG )
		{
			const char *tag = AutomaticTag(i);
			int link        = strcmp(tag, section->tag) != 0;

			ConvertOutputString("  ", 1);
			if( link )
				HrefOutputPass2(tag, "", "false", "");
			while( *tag == '_' )
				tag++;
			OutputString(tag);
			if( link )
				HrefEnd("\n");

			i++;
		}
	}


	// Header for this links
	ConvertOutputString("  ", 1);
	OutputString("This:");
	ConvertOutputString("  ", 1);

	// standard method to link to this section
	HrefOutputPass2(section->tag, "", "false", "");
	OutputString("section");
	HrefEnd(", ");

	// explicit link to this frame
	FormatOutput("<a href=\"%s\" target=\"_top\">", fileName);
	OutputString("frame</a>");

	// end of right justification
	OutputString("</div>\n");

	if( navigation )
		FormatOutput("<hr%s", Internal2Out("SelfTerminateCmd") );

	return;
}
