/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* Name of package */
#define PACKAGE "omhelp"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "bradbell@seanet.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "OMhelp"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "OMhelp 05-06-27"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "omhelp"

/* Define to the version of this package. */
#define PACKAGE_VERSION "05-06-27"

/* Version number of package */
#define VERSION "05-06-27"
