#line 2 "/home/bradbell/repo/omhelp.git/src/lex.tex.c"

#line 4 "/home/bradbell/repo/omhelp.git/src/lex.tex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer tex_create_buffer
#define yy_delete_buffer tex_delete_buffer
#define yy_flex_debug tex_flex_debug
#define yy_init_buffer tex_init_buffer
#define yy_flush_buffer tex_flush_buffer
#define yy_load_buffer_state tex_load_buffer_state
#define yy_switch_to_buffer tex_switch_to_buffer
#define yyin texin
#define yyleng texleng
#define yylex texlex
#define yylineno texlineno
#define yyout texout
#define yyrestart texrestart
#define yytext textext
#define yywrap texwrap
#define yyalloc texalloc
#define yyrealloc texrealloc
#define yyfree texfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE texrestart(texin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int texleng;

extern FILE *texin, *texout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up textext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up textext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via texrestart()), so that the user can continue scanning by
	 * just pointing texin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when textext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int texleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow texwrap()'s to do buffer switches
 * instead of setting up a fresh texin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void texrestart (FILE *input_file  );
void tex_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE tex_create_buffer (FILE *file,int size  );
void tex_delete_buffer (YY_BUFFER_STATE b  );
void tex_flush_buffer (YY_BUFFER_STATE b  );
void texpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void texpop_buffer_state (void );

static void texensure_buffer_stack (void );
static void tex_load_buffer_state (void );
static void tex_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER tex_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE tex_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE tex_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE tex_scan_bytes (yyconst char *bytes,int len  );

void *texalloc (yy_size_t  );
void *texrealloc (void *,yy_size_t  );
void texfree (void *  );

#define yy_new_buffer tex_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        texensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            tex_create_buffer(texin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        texensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            tex_create_buffer(texin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *texin = NULL, *texout = NULL;

typedef int yy_state_type;

extern int texlineno;

int texlineno = 1;

extern char *textext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr textext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up textext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	texleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 46
#define YY_END_OF_BUFFER 47
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[168] =
    {   0,
       44,   44,   47,   34,   45,   44,   38,   40,   45,   30,
       40,   40,   39,   37,   36,   45,   42,   31,   43,   35,
       41,   44,   33,    0,    0,   39,   39,   39,   37,    9,
        8,    5,    7,    6,   32,    2,    1,    3,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,    4,   39,   32,   32,   11,   32,   32,   32,   32,
       32,   32,   32,   32,   28,   21,   32,   32,   23,   32,
       32,   32,   12,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,    0,   14,   32,   16,   32,
       32,   32,   22,   32,   32,   32,   32,    0,   32,   32,

       32,   32,   20,   32,   32,   32,   32,    0,    0,   32,
       32,   32,   32,   32,   32,   32,   32,   32,    0,    0,
        0,    0,   32,   32,   32,   32,   32,   26,   32,    0,
        0,    0,    0,    0,    0,    0,   32,   19,   29,   32,
       32,   32,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   17,   18,   32,   25,   27,    0,   13,    0,
        0,   24,    0,    0,   15,   10,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    2,    2,    2,    2,    2,    2,    2,    3,    4,
        2,    2,    3,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    3,    5,    5,    6,    6,    7,    8,    5,    5,
        5,    9,    5,   10,   11,   12,    5,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,    5,
        5,    5,    5,    5,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       17,   18,   19,   20,   21,    5,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   16,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   16,   46,   47,   48,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2
    } ;

static yyconst YY_CHAR yy_meta[49] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    4
    } ;

static yyconst flex_uint16_t yy_base[172] =
    {   0,
        0,    0,  368,  369,  369,  364,  369,  369,   48,  369,
       38,  353,   41,    0,  369,   54,  369,  369,  369,  369,
      369,  362,  369,  102,  351,   92,  350,  349,    0,  369,
      369,  369,  369,  369,  352,  369,  369,  369,   98,   99,
      100,  101,  102,  103,  104,  105,  107,  106,  108,  110,
      119,  369,  347,  369,  114,  350,  113,  111,  109,  118,
      123,  121,  126,  129,  349,  348,  142,  144,  347,  146,
      147,  149,  346,  150,  151,  154,  153,  155,  156,  158,
      159,  161,  160,  164,  168,  332,  344,  165,  333,  172,
      169,  173,  332,  179,  174,  182,  186,  301,  188,  189,

      191,  194,  329,  195,  207,  197,  198,  314,  296,  199,
      200,  209,  206,  208,  211,  214,  216,  218,  292,  306,
      240,    0,  217,  228,  226,  233,  227,  318,  238,  288,
      279,  254,  247,  309,  265,  270,  253,  308,  306,  260,
      255,  261,  292,  263,  270,  283,  299,  275,  238,  271,
      271,  248,  369,  290,  266,  288,  281,  240,  369,  307,
      245,  271,  226,  273,  369,  369,  369,  343,  235,  346,
      349
    } ;

static yyconst flex_int16_t yy_def[172] =
    {   0,
      167,    1,  167,  167,  167,  167,  167,  167,  168,  167,
      167,  167,  167,  169,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  168,  167,  167,  167,  167,  169,  167,
      167,  167,  167,  167,  170,  167,  167,  167,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  167,  167,  167,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  167,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  167,  170,  170,

      170,  170,  170,  170,  170,  170,  170,  167,  167,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  167,  167,
      167,  171,  170,  170,  170,  170,  170,  170,  170,  167,
      167,  167,  167,  167,  167,  171,  170,  170,  170,  170,
      170,  170,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  170,  170,  170,  170,  167,  167,  167,
      167,  170,  167,  167,  167,  167,    0,  167,  167,  167,
      167
    } ;

static yyconst flex_uint16_t yy_nxt[418] =
    {   0,
        4,    5,    6,    7,    8,    5,    9,   10,    8,    8,
       11,   12,   13,    8,    8,   14,   15,   16,   17,   18,
       19,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   20,    8,   21,   23,   25,
       26,   23,   28,   26,   30,   30,   30,   30,   30,   31,
       31,   31,   30,   32,   30,   30,   30,   33,   34,   35,
       36,   37,   38,   30,   31,   35,   39,   40,   35,   41,
       42,   35,   43,   35,   35,   44,   45,   35,   46,   35,
       35,   47,   48,   49,   50,   35,   51,   35,   35,   31,

       52,   31,   23,   28,   26,   23,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       57,   54,   54,   55,   56,   62,   54,   54,   61,   54,
       75,   54,   66,   58,   54,   74,   64,   54,   59,   65,
       60,   72,   67,   70,   73,   68,   63,   69,   71,   77,
       54,   79,   54,   76,   54,   54,   80,   54,   54,   54,
       78,   54,   54,   54,   54,   82,   54,   54,   54,   54,
       83,   84,   54,   54,   87,   88,   54,   54,   85,   81,
       54,   54,   54,   90,   94,   95,   92,   54,   99,   96,
       54,  101,   89,   91,   54,   86,   54,   54,   93,   54,

      102,   97,   54,   54,  100,   54,   54,   54,   54,  104,
      106,  105,  103,  110,   54,   54,   54,   54,  117,   54,
      111,  107,   54,  113,   54,   54,   54,  118,  112,  115,
      123,  108,  114,  125,   54,   54,   54,   29,  116,  124,
      137,   54,  132,  127,  121,  122,   54,  164,  126,  129,
      133,  134,  135,  138,  140,  128,  132,  139,  134,  135,
      141,   54,  142,   54,  133,  134,  135,  146,   54,   54,
      161,  161,  146,  166,   54,  164,  147,  135,  154,   54,
      156,  161,  145,  155,  163,  146,  157,  161,  148,   54,
      149,  162,  165,  148,  150,  149,   54,  151,   54,  150,

      152,  146,  151,  161,  161,  152,  148,  161,  149,  146,
      159,  160,  150,  158,   54,  151,   54,  153,  152,  160,
      165,  145,  148,  144,  149,  143,   54,  131,  150,  130,
      148,  151,  149,  120,  152,  119,  150,   54,  109,  151,
       54,   54,  152,   24,   24,   24,   24,   35,   35,  136,
      136,  136,   54,   98,   54,   54,   54,   54,   54,   53,
       54,   53,   27,   27,   22,   27,   22,  167,    3,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,

      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167
    } ;

static yyconst flex_int16_t yy_chk[418] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,   11,
       11,    9,   13,   13,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,

       16,   16,   24,   26,   26,   24,   39,   40,   41,   42,
       43,   44,   45,   46,   48,   47,   49,   59,   50,   58,
       40,   57,   55,   39,   39,   45,   60,   51,   44,   62,
       59,   61,   48,   41,   63,   58,   47,   64,   42,   47,
       43,   55,   48,   50,   57,   48,   46,   49,   51,   61,
       67,   63,   68,   60,   70,   71,   64,   72,   74,   75,
       62,   77,   76,   78,   79,   68,   80,   81,   83,   82,
       70,   71,   84,   88,   75,   76,   85,   91,   72,   67,
       90,   92,   95,   78,   82,   83,   80,   94,   88,   84,
       96,   91,   77,   79,   97,   74,   99,  100,   81,  101,

       91,   85,  102,  104,   90,  106,  107,  110,  111,   94,
       96,   95,   92,   99,  113,  105,  114,  112,  106,  115,
      100,   96,  116,  102,  117,  123,  118,  107,  101,  105,
      112,   97,  104,  114,  125,  127,  124,  169,  105,  113,
      123,  126,  121,  116,  110,  111,  129,  161,  115,  118,
      121,  121,  121,  124,  126,  117,  132,  125,  133,  133,
      127,  137,  129,  141,  132,  132,  132,  135,  140,  142,
      149,  152,  145,  163,  155,  164,  135,  135,  137,  162,
      141,  149,  145,  140,  158,  146,  142,  152,  135,  157,
      135,  155,  161,  145,  135,  145,  156,  135,  154,  145,

      135,  147,  145,  151,  150,  145,  146,  148,  146,  160,
      144,  147,  146,  143,  139,  146,  138,  136,  146,  160,
      164,  134,  147,  131,  147,  130,  128,  120,  147,  119,
      160,  147,  160,  109,  147,  108,  160,  103,   98,  160,
       93,   89,  160,  168,  168,  168,  168,  170,  170,  171,
      171,  171,   87,   86,   73,   69,   66,   65,   56,   53,
       35,   28,   27,   25,   22,   12,    6,    3,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,

      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int tex_flex_debug;
int tex_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *textext;
#line 1 "/home/bradbell/repo/omhelp.git/src/latex.l"
#line 2 "/home/bradbell/repo/omhelp.git/src/latex.l"
/* ----------------------------------------------------------------------------
OMhelp: Language Independent Embedded Documentation
          Copyright (C) 1998-2018 Bradley M. Bell
OMhelp is distributed under the terms of the
            GNU General Public License Version 2.
---------------------------------------------------------------------------- */
/*
Lexical analyizer for a subset of Latex Commands
$begin  LatexLexPut$$
$spell
	const
	ntoken
$$

$section Set Input Characters Corresponding Latex Lexical Analyzer$$

$head Syntax$$
$codei/LatexLexPut(/line/, /input/)/$$


$head Description$$
The Latex lexical analyzer reads its data from memory.
This call sets the input data to the $code const$$ '\0' terminated
character vector specified by $icode input$$.
The integer $icode line$$ specifies the line
number in the file $cref/InputName()/InputName/$$
where $icode input$$ started.

$head Memory Allocation$$
This call allocates memory using $cref AllocMem$$.
This memory is freed when the Latex lexical analyzer returns
$code CHAR_ENDINPUT_lex$$.


$end
------------------------------------------------------------------------
$begin LatexLexHistory$$
$spell
	ntoken
$$

$section Recall Tokens Recently Returned To Parser$$

$head Syntax$$
$codei/LatexLexHistory(/number/, /length/, /line/, /token/)/$$


$head Description$$
The return value of $code LatexLexHistory$$ is a $code int$$
which we refer to as $icode ntoken$$.
It specifies the actual number of tokens returned
by $code LatexLexHistory$$.
$codei/

int /number/
/$$
The value $icode number$$ specifies the
maximum number of tokens to return.
The value $icode ntoken$$ will be less than or
equal $icode number$$.
$codei/

int /length/
/$$
The value $icode length$$ specifies the
maximum number of character to return for each token.
$codei%

int *%line%
%$$
The array $icode line$$ must have at least $icode number$$
elements in it.
The input value of the elements of $icode line$$ does not matter.
For $math% i=0,...,ntoken-1 %$$
the value of $icode/line/[/i/]/$$ is set to the line
number where the token
$icode/token/[/i/]/$$ appeared in the
file $cref/InputName()/InputName/$$.
$codei%

char **%token%
%$$
The array $icode token$$ must have at least $icode number$$
elements in it.
Each element of $icode token$$ is in turn an array of characters
with at least $icode length$$ elements in it.
The input value of the elements of $icode token$$ does not matter.
For $math% i=0,...,ntoken-1 %$$,
the value of $icode/token/[/i/]/$$ is a '\0' terminated
character vector containing a previous token.
The tokens are returned
in reverse order of how they appeared in the input.
If a token is longer than $math% length-1 %$$ characters,
only the first $math% length-1 %$$ characters are included.

$end
*/
# include "LatexLexPut.h"
# include "LatexLexHistory.h"

#ifdef WIN32
# include <conio.h>
#endif

# include <stdlib.h>
# include <string.h>
# include <assert.h>
# include <ctype.h>

# include "LatexMacro.h"
# include "fatalerr.h"
# include "str_alloc.h"
# include "allocmem.h"
# include "input.h"
# include "int2str.h"
# include "LatexAtomic.h"

# include "TexStype.h"
# define YYSTYPE  TexStype
# ifdef WIN32
# define YY_NO_UNISTD_H
# endif

// see http://sourceware.org/ml/gdb-patches/2010-01/msg00372.html
# define YY_NO_INPUT

// maximum input token buffer sizes
# define MAX_TOKEN_LENGTH 100
# define MAX_TOKEN_NUMBER 10


// print debugging information
# define DEBUG_TOKENS 0

// automatically generated include file generated by yacc from latex.y
# include "latex.h"


static void SetTexLval(const char *token, const char *str);

// define the character input routine
# undef YY_INPUT
# define YY_INPUT(buf, result, max_size) \
{	assert( max_size != 0 );         \
	buf[0]  = LatexMacroGetCh();     \
	result = 1;                      \
}

static char Cmd_Bracket_Mode = '\0';

/*
Source:  http://www.w3.org/TR/MathML2/isodia.html
Source:  http://www.w3.org/TR/MathML2/byalpha.html
Date:    02-11-21
Section: IDODIA Characters and Glyphs
Chapter: Entities, Characters and Fonts
*/
static struct cmdover {
	char *name;
	char *mathml;
} Diacritical[] = {
	// Latex       MathML
	{ "acute",  "&#x000B4;" },      // DiacriticalAcute = x000B4
	{ "bar",    "&#x000AF;" },      // OverBar          = x000AF
	{ "breve",  "&#x002D8;" },      // Breve            = x002D8
	{ "check",  "&#x002C7;" },      // caron            = x002C7
	{ "ddot",   "&#x000A8;" },      // Dot              = x000A8
	{ "dot",    "&#x002D9;" },      // dot              = x002D9
	{ "hat",    "&#x0005E;" },      // circ             = x0005E
	{ "grave",  "&#x00060;" },      // grave            = x00060
	{ "tilde",  "&#x002DC;" },      // tilde            = x002DC
	{ "vec",    "&#x021C0;" }       // RightVector      = x021C0
};
static size_t NDiacritical =
	sizeof(Diacritical) / sizeof(Diacritical[0]);

/***************************************************************************/
#line 795 "/home/bradbell/repo/omhelp.git/src/lex.tex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int texlex_destroy (void );

int texget_debug (void );

void texset_debug (int debug_flag  );

YY_EXTRA_TYPE texget_extra (void );

void texset_extra (YY_EXTRA_TYPE user_defined  );

FILE *texget_in (void );

void texset_in  (FILE * _in_str  );

FILE *texget_out (void );

void texset_out  (FILE * _out_str  );

			int texget_leng (void );

char *texget_text (void );

int texget_lineno (void );

void texset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int texwrap (void );
#else
extern int texwrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT

#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( textext, (size_t) texleng, 1, texout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( texin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( texin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, texin)) == 0 && ferror(texin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(texin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int texlex (void);

#define YY_DECL int texlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after textext and texleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! texin )
			texin = stdin;

		if ( ! texout )
			texout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			texensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				tex_create_buffer(texin,YY_BUF_SIZE );
		}

		tex_load_buffer_state( );
		}

	{
#line 201 "/home/bradbell/repo/omhelp.git/src/latex.l"


	// special commands with separate constructions
#line 1015 "/home/bradbell/repo/omhelp.git/src/lex.tex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of textext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 168 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 369 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 204 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		assert( strlen(textext) == 2 );

		SetTexLval(textext, NULL);
		return CMD_BACKSLASH_lex;
	}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 210 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		assert( strlen(textext) == 2 );

		SetTexLval(textext, NULL);
		return CMD_LEFTBRACKET_lex;
	}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 216 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		assert( strlen(textext) == 2 );

		SetTexLval(textext, NULL);
		return CMD_RIGHTBRACKET_lex;
	}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 222 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		assert( strlen(textext) == 2 );

		// double vertical line
		SetTexLval(textext, "&#x02016;"); // Vert = x02016

		return SYM_ENCLOSE_lex;
	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 230 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		assert( strlen(textext) == 2 );
		SetTexLval(textext, NULL);
		return CMD_COMMA_lex;
	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 235 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		assert( strlen(textext) == 2 );
		SetTexLval(textext, NULL);
		return CMD_SEMICOLON_lex;
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 240 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		assert( strlen(textext) == 2 );
		SetTexLval(textext, NULL);
		return CMD_COLON_lex;
	}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 245 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		assert( strlen(textext) == 2 );

		SetTexLval(textext, textext + 1);
		return CMD_CHAR_lex;
	}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 251 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		fataltex(
			"The text '",
			textext,
			"' is not a valid Latex command.",
			NULL
		);
	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 259 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		Cmd_Bracket_Mode = '[';
		return CMD_BEGIN_ARRAY_lex;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 264 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, "bold" );
		return CMD_FONT_lex;
	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 268 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, "italic" );
		return CMD_FONT_lex;
	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 272 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		return CMD_END_ARRAY_lex;
	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 276 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		return CMD_FRAC_lex;
	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 280 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		size_t len = strlen(textext);

		assert( strncmp( textext, "\\hspace{", 8 ) == 0 );
		assert( textext[len-1] == '}' );

		textext[len-1] = '\0';
		SetTexLval(textext + 8, textext + 8);
		textext[len-1] = '}';

		return CMD_HSPACE_lex;
	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 292 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		return CMD_LEFT_lex;
	}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 296 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		size_t len = strlen(textext);

		assert( len >= 10 );
		assert( textext[len-1] == '}' );

		textext[len-1] = '\0';
		SetTexLval(textext + 8 , textext + 8);
		textext[len-1] = '}';

		return CMD_MATHML_lex;
	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 308 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		return CMD_OVERBRACE_lex;
	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 312 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		return CMD_OVERLINE_lex;
	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 316 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		return CMD_RIGHT_lex;
	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 320 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, "sans-serif" );
		return CMD_FONT_lex;
	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 324 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		Cmd_Bracket_Mode = '[';
		return CMD_SQRT_lex;
	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 329 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, "monospace" );
		return CMD_FONT_lex;
	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 333 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		return CMD_UNDERBRACE_lex;
	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 337 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		return CMD_UNDERLINE_lex;
	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 341 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		return CMD_WIDEHAT_lex;
	}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 345 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		return CMD_WIDETILDE_lex;
	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 349 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, "normal" );
		return CMD_FONT_lex;
	}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 353 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		return CMD_STACKREL_lex;
	}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 357 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		return CHAR_AMPERSAND_lex;
	}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 361 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
		SetTexLval(textext, NULL);
		return CHAR_CARET_lex;
	}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 365 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
	const char *name;
	const char  *str;
	int        token;
	size_t         i;

	name = textext + 1;

	str = LatexAtomic(name, &token);
	if( str != NULL )
	{	SetTexLval(textext, str);
		return token;
	}
	for(i = 0; i < NDiacritical; i++)
	{	if( strcmp(Diacritical[i].name, name) == 0 )
		{	SetTexLval(textext, Diacritical[i].mathml);
			return CMD_DIACRITICAL_lex;
		}
	}

	fataltex(
		textext,
		" is not a valid command in OMhelp's Latex mode.",
		NULL
	);
}
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 391 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
	// ignore
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 394 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
	SetTexLval("CHAR_ENDINPUT_lex", NULL);
	return CHAR_ENDINPUT_lex;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 398 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
	SetTexLval(textext, NULL);
	return CHAR_LEFTBRACE_lex;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 402 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
	if( Cmd_Bracket_Mode == '[' )
	{	SetTexLval(textext, NULL);
		Cmd_Bracket_Mode = ']';
		return CHAR_LEFTBRACKET_lex;
	}
	if( Cmd_Bracket_Mode == ']' ) fatalerr(
		"another '[' occurred while looking for the ']'\n",
		"that terminates a command argument started with a '['",
		NULL
	);
	SetTexLval(textext, textext);
	return CHAR_OPERATOR_lex;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 416 "/home/bradbell/repo/omhelp.git/src/latex.l"
{

# ifndef NDEBUG
	size_t i;
	i = strlen(textext);
	assert( i > 0 );
# endif

	// check begins with a letter
	assert( isalpha((int) textext[0] ) );

	SetTexLval(textext, textext);

	return CHAR_LETTERS_lex;
}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 431 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
	// ignore
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 434 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
	SetTexLval(textext, textext);
	return NUMBER_lex;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 438 "/home/bradbell/repo/omhelp.git/src/latex.l"
{	// operators that do not need conversion to Unicode

	SetTexLval(textext, textext);
	return CHAR_OPERATOR_lex;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 443 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
	SetTexLval(textext, NULL);
	return CHAR_RIGHTBRACE_lex;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 447 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
	if( Cmd_Bracket_Mode == ']' )
	{	SetTexLval(textext, NULL);
		Cmd_Bracket_Mode = '\0';
		return CHAR_RIGHTBRACKET_lex;
	}
	SetTexLval(textext, textext);
	return CHAR_OPERATOR_lex;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 456 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
	SetTexLval(textext, NULL);
	return CHAR_UNDERBAR_lex;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 460 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
	// ignore
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 464 "/home/bradbell/repo/omhelp.git/src/latex.l"
{
	fataltex(
		"The character with ascii code ",
		int2str( (int) textext[0] ),
		"\nis not a valid Latex input character.",
		NULL
	);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 473 "/home/bradbell/repo/omhelp.git/src/latex.l"
ECHO;
	YY_BREAK
#line 1528 "/home/bradbell/repo/omhelp.git/src/lex.tex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed texin at a new source and called
			 * texlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = texin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( texwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * textext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of texlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					texrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			texrestart(texin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) texrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;

	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 2);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 168 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 2;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 168 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 167);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;

	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					texrestart(texin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( texwrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve textext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void texrestart  (FILE * input_file )
{

	if ( ! YY_CURRENT_BUFFER ){
        texensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            tex_create_buffer(texin,YY_BUF_SIZE );
	}

	tex_init_buffer(YY_CURRENT_BUFFER,input_file );
	tex_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 *
 */
    void tex_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		texpop_buffer_state();
	 *		texpush_buffer_state(new_buffer);
     */
	texensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	tex_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (texwrap()) processing, but the only time this flag
	 * is looked at is after texwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void tex_load_buffer_state  (void)
{
	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	texin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 *
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE tex_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) texalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in tex_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) texalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in tex_create_buffer()" );

	b->yy_is_our_buffer = 1;

	tex_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with tex_create_buffer()
 *
 */
    void tex_delete_buffer (YY_BUFFER_STATE  b )
{

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		texfree((void *) b->yy_ch_buf  );

	texfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a texrestart() or at EOF.
 */
    static void tex_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;

	tex_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then tex_init_buffer was _probably_
     * called from texrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 *
 */
    void tex_flush_buffer (YY_BUFFER_STATE  b )
{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		tex_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *
 */
void texpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
	if (new_buffer == NULL)
		return;

	texensure_buffer_stack();

	/* This block is copied from tex_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from tex_switch_to_buffer. */
	tex_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *
 */
void texpop_buffer_state (void)
{
	if (!YY_CURRENT_BUFFER)
		return;

	tex_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		tex_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void texensure_buffer_stack (void)
{
	int num_to_alloc;

	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)texalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in texensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)texrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in texensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE tex_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) texalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in tex_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	tex_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to texlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 *
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       tex_scan_bytes() instead.
 */
YY_BUFFER_STATE tex_scan_string (yyconst char * yystr )
{

	return tex_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to texlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE tex_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) _yybytes_len + 2;
	buf = (char *) texalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in tex_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = tex_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in tex_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up textext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		textext[texleng] = (yy_hold_char); \
		(yy_c_buf_p) = textext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		texleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 *
 */
int texget_lineno  (void)
{

    return texlineno;
}

/** Get the input stream.
 *
 */
FILE *texget_in  (void)
{
        return texin;
}

/** Get the output stream.
 *
 */
FILE *texget_out  (void)
{
        return texout;
}

/** Get the length of the current token.
 *
 */
int texget_leng  (void)
{
        return texleng;
}

/** Get the current token.
 *
 */

char *texget_text  (void)
{
        return textext;
}

/** Set the current line number.
 * @param _line_number line number
 *
 */
void texset_lineno (int  _line_number )
{

    texlineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 *
 * @see tex_switch_to_buffer
 */
void texset_in (FILE *  _in_str )
{
        texin = _in_str ;
}

void texset_out (FILE *  _out_str )
{
        texout = _out_str ;
}

int texget_debug  (void)
{
        return tex_flex_debug;
}

void texset_debug (int  _bdebug )
{
        tex_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from texlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    texin = stdin;
    texout = stdout;
#else
    texin = NULL;
    texout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * texlex_init()
     */
    return 0;
}

/* texlex_destroy is for both reentrant and non-reentrant scanners. */
int texlex_destroy  (void)
{

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		tex_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		texpop_buffer_state();
	}

	/* Destroy the stack itself. */
	texfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * texlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *texalloc (yy_size_t  size )
{
			return malloc(size);
}

void *texrealloc  (void * ptr, yy_size_t  size )
{

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void texfree (void * ptr )
{
			free( (char *) ptr );	/* see texrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 473 "/home/bradbell/repo/omhelp.git/src/latex.l"


/****************************************************************************/

static char Token[MAX_TOKEN_NUMBER][MAX_TOKEN_LENGTH];
static int  TokenLine[MAX_TOKEN_NUMBER];
static int  TokenStart = 0;
static int  TokenNext  = 0;

static void SetTexLval(const char *token, const char *str)
{	int i;

	assert( token != NULL );

	if( DEBUG_TOKENS )
		printf("\nTexLex(%s) ", token);

	texlval.line  = LatexMacroInputLine();

	if( str == NULL )
		texlval.str = NULL;
	else	texlval.str = str_alloc(str);

	texlval.data  = 0;
	texlval.extra = NULL;
	texlval.next  = NULL;

	// copy the token into the next slot
	i = strlen(token);
	if( i >= MAX_TOKEN_LENGTH )
		i = MAX_TOKEN_LENGTH - 1;

	Token[TokenNext][i] = '\0';
	while( i > 0 )
	{	--i;
		Token[TokenNext][i] = token[i];
	}
	TokenLine[TokenNext] = LatexMacroInputLine();

	// increment the next and start pointers
	TokenNext = (TokenNext + 1) % MAX_TOKEN_NUMBER;
	if( TokenStart == TokenNext )
		TokenStart = (TokenStart + 1) % MAX_TOKEN_NUMBER;
	assert( TokenStart != TokenNext );


	if( Cmd_Bracket_Mode == '[' )
		Cmd_Bracket_Mode = '\0';

	return;

}

void LatexLexPut(int line, const char *input)
{
	LatexMacroUserInput(line, input);

	TokenStart  = 0;
	TokenNext   = 0;
	return;
}


int LatexLexHistory(int number, int length, int *line, char **token)
{	int ntoken;
	int i;
	int next;

	ntoken = 0;
	next   = TokenNext;
	while( next != TokenStart && ntoken < number )
	{	next--;
		if( next < 0 )
			next = MAX_TOKEN_NUMBER - 1;

		i = strlen(Token[next]);
		if( i >= length )
			i = length - 1;
		token[ntoken][i] = 0;
		while( i > 0 )
		{	--i;
			token[ntoken][i] = Token[next][i];
		}
		line[ntoken] = TokenLine[next];
		ntoken++;
	}
	return ntoken;
}
