#define yy_create_buffer tex_create_buffer
#define yy_delete_buffer tex_delete_buffer
#define yy_scan_buffer tex_scan_buffer
#define yy_scan_string tex_scan_string
#define yy_scan_bytes tex_scan_bytes
#define yy_flex_debug tex_flex_debug
#define yy_init_buffer tex_init_buffer
#define yy_flush_buffer tex_flush_buffer
#define yy_load_buffer_state tex_load_buffer_state
#define yy_switch_to_buffer tex_switch_to_buffer
#define yyin texin
#define yyleng texleng
#define yylex texlex
#define yyout texout
#define yyrestart texrestart
#define yytext textext
#define yywrap texwrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
static yyconst short int yy_accept[165] =
    {   0,
       43,   43,   46,   33,   44,   43,   37,   39,   44,   29,
       39,   39,   38,   36,   35,   44,   41,   30,   42,   34,
       40,   43,   32,    0,    0,   38,   38,   38,   36,    9,
        8,    5,    7,    6,   31,    2,    1,    3,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
        4,   38,   31,   31,   11,   31,   31,   31,   31,   31,
       31,   31,   27,   20,   31,   31,   22,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,    0,   13,   31,   15,   31,   31,   31,   21,
       31,   31,   31,   31,    0,   31,   31,   31,   31,   19,

       31,   31,   31,   31,    0,    0,   31,   31,   31,   31,
       31,   31,   31,   31,   31,    0,    0,    0,    0,   31,
       31,   31,   31,   31,   25,   31,    0,    0,    0,    0,
        0,    0,    0,   31,   18,   28,   31,   31,   31,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   16,
       17,   31,   24,   26,    0,   12,    0,    0,   23,    0,
        0,   14,   10,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    2,    2,    2,    2,    2,    2,    2,    3,    4,
        2,    2,    3,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    3,    5,    5,    6,    6,    7,    8,    5,    5,
        5,    9,    5,   10,   11,   12,    5,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,    5,
        5,    5,    5,    5,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       17,   18,   19,   20,   21,    5,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   16,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   16,   46,   47,   48,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2
    } ;

static yyconst int yy_meta[49] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    4
    } ;

static yyconst short int yy_base[169] =
    {   0,
        0,    0,  363,  364,  364,  359,  364,  364,   48,  364,
       38,  348,   41,    0,  364,   54,  364,  364,  364,  364,
      364,  357,  364,  102,  346,   92,  345,  344,    0,  364,
      364,  364,  364,  364,  347,  364,  364,  364,   98,   99,
      100,  101,  102,  104,  103,  106,  107,  108,  109,  105,
      364,  342,  364,  113,  345,  112,  110,  114,  122,  111,
      120,  133,  344,  343,  118,  143,  342,  144,  145,  146,
      121,  148,  149,  150,  151,  153,  154,  155,  157,  159,
      166,  164,  328,  340,  165,  339,  168,  170,  169,  328,
      173,  175,  177,  178,  298,  179,  187,  185,  188,  325,

      190,  198,  194,  199,  311,  293,  191,  201,  203,  202,
      205,  206,  211,  213,  217,  292,  307,  239,    0,  224,
      229,  225,  218,  226,  318,  234,  287,  279,  251,  233,
      310,  262,  273,  230,  311,  309,  249,  252,  257,  291,
      261,  267,  278,  286,  274,  235,  272,  268,  245,  364,
      287,  258,  285,  281,  242,  364,  302,  229,  273,  228,
      269,  364,  364,  364,  338,  268,  341,  344
    } ;

static yyconst short int yy_def[169] =
    {   0,
      164,    1,  164,  164,  164,  164,  164,  164,  165,  164,
      164,  164,  164,  166,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  165,  164,  164,  164,  164,  166,  164,
      164,  164,  164,  164,  167,  164,  164,  164,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      164,  164,  164,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  164,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  164,  167,  167,  167,  167,  167,

      167,  167,  167,  167,  164,  164,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  164,  164,  164,  168,  167,
      167,  167,  167,  167,  167,  167,  164,  164,  164,  164,
      164,  164,  168,  167,  167,  167,  167,  167,  167,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      167,  167,  167,  167,  164,  164,  164,  164,  167,  164,
      164,  164,  164,    0,  164,  164,  164,  164
    } ;

static yyconst short int yy_nxt[413] =
    {   0,
        4,    5,    6,    7,    8,    5,    9,   10,    8,    8,
       11,   12,   13,    8,    8,   14,   15,   16,   17,   18,
       19,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   20,    8,   21,   23,   25,
       26,   23,   28,   26,   30,   30,   30,   30,   30,   31,
       31,   31,   30,   32,   30,   30,   30,   33,   34,   35,
       36,   37,   38,   30,   31,   35,   39,   35,   35,   40,
       41,   35,   42,   35,   35,   43,   44,   35,   45,   35,
       35,   46,   47,   48,   49,   35,   50,   35,   35,   31,

       51,   31,   23,   28,   26,   23,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   54,   55,   60,   53,   59,   53,   53,
       53,   72,   56,   64,   69,   62,   71,   57,   63,   58,
       70,   53,   68,   65,   61,   76,   66,   67,   74,   73,
       75,   53,   53,   53,   53,   78,   53,   53,   53,   53,
       77,   53,   53,   53,   79,   53,   83,   53,   80,   81,
       85,   84,   53,   53,   53,   82,   53,   53,   53,   87,
       91,   53,   89,   53,   92,   53,   53,   53,   96,   86,
       88,   93,   98,   53,   90,   53,   53,   94,   53,   53,

       97,   99,   53,  101,  107,  103,   53,   53,  100,   53,
       53,   53,  102,   53,   53,  114,  104,  110,  108,   53,
      112,   53,  109,  105,  120,   53,   53,  111,  115,  113,
      122,  161,   53,   53,   53,  121,  118,   53,   53,  137,
      124,  129,   53,  123,  131,  132,  119,  134,  126,  130,
      131,  132,  125,  129,  135,  151,  136,   53,  139,  138,
       53,  130,  131,  132,  143,   53,   53,  158,  158,  143,
       29,  161,  152,  144,  132,  163,  162,  153,  158,  142,
      143,   53,  154,  159,  158,  145,  160,  146,  143,   53,
      145,  147,  146,   53,  148,   53,  147,  149,  157,  148,

      158,  145,  149,  146,  143,  158,  158,  147,  156,  145,
      148,  146,  155,  149,  157,  147,  162,   53,  148,   53,
      150,  149,  142,  141,  140,  145,   53,  146,  128,  127,
      117,  147,  116,   53,  148,  106,   53,  149,   24,   24,
       24,   24,   35,   35,  133,  133,  133,   53,   53,   95,
       53,   53,   53,   53,   52,   53,   52,   27,   27,   22,
       27,   22,  164,    3,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,

      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164
    } ;

static yyconst short int yy_chk[413] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,   11,
       11,    9,   13,   13,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,

       16,   16,   24,   26,   26,   24,   39,   40,   41,   42,
       43,   45,   44,   50,   46,   47,   48,   49,   57,   60,
       56,   54,   58,   39,   39,   44,   65,   43,   61,   71,
       59,   57,   40,   47,   50,   46,   56,   41,   46,   42,
       54,   62,   49,   47,   45,   61,   47,   48,   59,   58,
       60,   66,   68,   69,   70,   65,   72,   73,   74,   75,
       62,   76,   77,   78,   66,   79,   71,   80,   68,   69,
       73,   72,   82,   85,   81,   70,   87,   89,   88,   75,
       79,   91,   77,   92,   80,   93,   94,   96,   85,   74,
       76,   81,   88,   98,   78,   97,   99,   82,  101,  107,

       87,   88,  103,   91,   96,   93,  102,  104,   89,  108,
      110,  109,   92,  111,  112,  103,   93,   99,   97,  113,
      102,  114,   98,   94,  109,  115,  123,  101,  104,  102,
      111,  158,  120,  122,  124,  110,  107,  121,  134,  123,
      113,  118,  126,  112,  130,  130,  108,  120,  115,  118,
      118,  118,  114,  129,  121,  134,  122,  137,  126,  124,
      138,  129,  129,  129,  132,  139,  152,  146,  149,  142,
      166,  161,  137,  132,  132,  160,  158,  138,  146,  142,
      143,  159,  139,  152,  149,  132,  155,  132,  144,  154,
      142,  132,  142,  153,  132,  151,  142,  132,  144,  142,

      148,  143,  142,  143,  157,  147,  145,  143,  141,  144,
      143,  144,  140,  143,  157,  144,  161,  136,  144,  135,
      133,  144,  131,  128,  127,  157,  125,  157,  117,  116,
      106,  157,  105,  100,  157,   95,   90,  157,  165,  165,
      165,  165,  167,  167,  168,  168,  168,   86,   84,   83,
       67,   64,   63,   55,   52,   35,   28,   27,   25,   22,
       12,    6,    3,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,

      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "latex.l"
#define INITIAL 0
#line 2 "latex.l"
// BEGIN SHORT COPYRIGHT
/* -----------------------------------------------------------------------
OMhelp: Source Code -> Help Files: Copyright (C) 1998-2004 Bradley M. Bell

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
------------------------------------------------------------------------ */
// END SHORT COPYRIGHT
/*
Lexical analyizer for a subset of Latex Commands
$begin  LatexLexPut$$
$spell
	const
	ntoken
$$

$section Set Input Characters Corresponding Latex Lexical Analyzer$$

$table
$bold Syntax$$
$cend $syntax/LatexLexPut(/line/, /input/)/$$
$tend

$head Description$$
The Latex lexical analyzer reads its data from memory.
This call sets the input data to the $code const$$ '\0' terminated
character vector specified by $italic input$$.
The integer $italic line$$ specifies the line
number in the file $cref/InputName()/InputName/$$
where $italic input$$ started.

$head Memory Allocation$$
This call allocates memory using $cref AllocMem$$.
This memory is freed when the Latex lexical analyzer returns
$code CHAR_ENDINPUT_lex$$.


$end
------------------------------------------------------------------------
$begin LatexLexHistory$$
$spell
	ntoken
$$

$section Recall Tokens Recently Returned To Parser$$

$table
$bold Syntax$$
$cend $syntax/LatexLexHistory(/number/, /length/, /line/, /token/)/$$
$tend

$head Description$$
The return value of $code LatexLexHistory$$ is a $code int$$
which we refer to as $italic ntoken$$.
It specifies the actual number of tokens returned
by $code LatexLexHistory$$.
$syntax/

int /number/
/$$
The value $italic number$$ specifies the
maximum number of tokens to return.
The value $italic ntoken$$ will be less than or
equal $italic number$$.
$syntax/

int /length/
/$$
The value $italic length$$ specifies the
maximum number of character to return for each token.
$syntax%

int *%line%
%$$
The array $italic line$$ must have at least $italic number$$
elements in it.
The input value of the elements of $italic line$$ does not matter.
For $math% i=0,...,ntoken-1 %$$
the value of $syntax//line/[/i/]/$$ is set to the line
number where the token
$syntax//token/[/i/]/$$ appeared in the
file $cref/InputName()/InputName/$$.
$syntax%

char **%token%
%$$
The array $italic token$$ must have at least $italic number$$
elements in it.
Each element of $italic token$$ is in turn an array of characters
with at least $italic length$$ elements in it.
The input value of the elements of $italic token$$ does not matter.
For $math% i=0,...,ntoken-1 %$$,
the value of $syntax//token/[/i/]/$$ is a '\0' terminated
character vector containing a previous token.
The tokens are returned
in reverse order of how they appeared in the input.
If a token is longer than $math% length-1 %$$ characters,
only the first $math% length-1 %$$ characters are included.

$end
*/
# include "LatexLexPut.h"
# include "LatexLexHistory.h"

#ifdef WIN32
# include <conio.h>
#endif

# include <stdlib.h>
# include <string.h>
# include <assert.h>
# include <ctype.h>

# include "LatexMacro.h"
# include "fatalerr.h"
# include "str_alloc.h"
# include "allocmem.h"
# include "input.h"
# include "int2str.h"
# include "LatexAtomic.h"

# include "TexStype.h"
# define YYSTYPE  TexStype

// maximum input token buffer sizes
# define MAX_TOKEN_LENGTH 100
# define MAX_TOKEN_NUMBER 10


// print debugging information
# define DEBUG_TOKENS 0

// automatically generated include file generated by yacc from latex.y
# include "latex.h"


static void SetTexLval(const char *token, const char *str);

// define the character input routine
# undef YY_INPUT
# define YY_INPUT(buf, result, max_size) \
{	assert( max_size != 0 );         \
	buf[0]  = LatexMacroGetCh();     \
	result = 1;                      \
}

static char Cmd_Bracket_Mode = '\0';

/*
Source:  http://www.w3.org/TR/MathML2/isodia.html
Source:  http://www.w3.org/TR/MathML2/byalpha.html
Date:    02-11-21
Section: IDODIA Characters and Glyphs
Chapter: Entities, Characters and Fonts
*/
static struct cmdover {
	char *name;
	char *mathml;
} Diacritical[] = {
	// Latex       MathML
	{ "acute",  "&#x000B4;" },      // DiacriticalAcute = x000B4
	{ "bar",    "&#x000AF;" },      // OverBar          = x000AF
	{ "breve",  "&#x002D8;" },      // Breve            = x002D8
	{ "check",  "&#x002C7;" },      // caron            = x002C7
	{ "ddot",   "&#x000A8;" },      // Dot              = x000A8
	{ "dot",    "&#x002D9;" },      // dot              = x002D9
	{ "hat",    "&#x0005E;" },      // circ             = x0005E
	{ "grave",  "&#x00060;" },      // grave            = x00060
	{ "tilde",  "&#x002DC;" },      // tilde            = x002DC
	{ "vec",    "&#x021C0;" }       // RightVector      = x021C0
};
static size_t NDiacritical =
	sizeof(Diacritical) / sizeof(Diacritical[0]);

/***************************************************************************/
#define YY_NO_UNPUT 1
#line 721 "lex.tex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 214 "latex.l"


	// special commands with separate constructions
#line 887 "lex.tex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 165 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 364 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 217 "latex.l"
{
		assert( strlen(yytext) == 2 );

		SetTexLval(yytext, NULL);
		return CMD_BACKSLASH_lex;
	}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 223 "latex.l"
{
		assert( strlen(yytext) == 2 );

		SetTexLval(yytext, NULL);
		return CMD_LEFTBRACKET_lex;
	}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 229 "latex.l"
{
		assert( strlen(yytext) == 2 );

		SetTexLval(yytext, NULL);
		return CMD_RIGHTBRACKET_lex;
	}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 235 "latex.l"
{
		assert( strlen(yytext) == 2 );

		// double vertical line
		SetTexLval(yytext, "&#x02016;"); // Vert = x02016

		return SYM_ENCLOSE_lex;
	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 243 "latex.l"
{
		assert( strlen(yytext) == 2 );
		SetTexLval(yytext, NULL);
		return CMD_COMMA_lex;
	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 248 "latex.l"
{
		assert( strlen(yytext) == 2 );
		SetTexLval(yytext, NULL);
		return CMD_SEMICOLON_lex;
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 253 "latex.l"
{
		assert( strlen(yytext) == 2 );
		SetTexLval(yytext, NULL);
		return CMD_COLON_lex;
	}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 258 "latex.l"
{
		assert( strlen(yytext) == 2 );

		SetTexLval(yytext, yytext + 1);
		return CMD_CHAR_lex;
	}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 264 "latex.l"
{
		fataltex(
			"The text '",
			yytext,
			"' is not a valid Latex command.",
			NULL
		);
	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 272 "latex.l"
{
		SetTexLval(yytext, NULL);
		Cmd_Bracket_Mode = '[';
		return CMD_BEGIN_ARRAY_lex;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 277 "latex.l"
{
		SetTexLval(yytext, "bold" );
		return CMD_FONT_lex;
	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 281 "latex.l"
{
		SetTexLval(yytext, NULL);
		return CMD_END_ARRAY_lex;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 285 "latex.l"
{
		SetTexLval(yytext, NULL);
		return CMD_FRAC_lex;
	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 289 "latex.l"
{
		size_t len = strlen(yytext);

		assert( strncmp( yytext, "\\hspace{", 8 ) == 0 );
		assert( yytext[len-1] == '}' );

		yytext[len-1] = '\0';
		SetTexLval(yytext + 8, yytext + 8);
		yytext[len-1] = '}';

		return CMD_HSPACE_lex;
	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 301 "latex.l"
{
		SetTexLval(yytext, NULL);
		return CMD_LEFT_lex;
	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 305 "latex.l"
{
		size_t len = strlen(yytext);

		assert( len >= 10 );
		assert( yytext[len-1] == '}' );

		yytext[len-1] = '\0';
		SetTexLval(yytext + 8 , yytext + 8);
		yytext[len-1] = '}';

		return CMD_MATHML_lex;
	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 317 "latex.l"
{
		SetTexLval(yytext, NULL);
		return CMD_OVERBRACE_lex;
	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 321 "latex.l"
{
		SetTexLval(yytext, NULL);
		return CMD_OVERLINE_lex;
	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 325 "latex.l"
{
		SetTexLval(yytext, NULL);
		return CMD_RIGHT_lex;
	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 329 "latex.l"
{
		SetTexLval(yytext, "sans-serif" );
		return CMD_FONT_lex;
	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 333 "latex.l"
{
		SetTexLval(yytext, NULL);
		Cmd_Bracket_Mode = '[';
		return CMD_SQRT_lex;
	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 338 "latex.l"
{
		SetTexLval(yytext, "monospace" );
		return CMD_FONT_lex;
	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 342 "latex.l"
{
		SetTexLval(yytext, NULL);
		return CMD_UNDERBRACE_lex;
	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 346 "latex.l"
{
		SetTexLval(yytext, NULL);
		return CMD_UNDERLINE_lex;
	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 350 "latex.l"
{
		SetTexLval(yytext, NULL);
		return CMD_WIDEHAT_lex;
	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 354 "latex.l"
{
		SetTexLval(yytext, NULL);
		return CMD_WIDETILDE_lex;
	}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 358 "latex.l"
{
		SetTexLval(yytext, "normal" );
		return CMD_FONT_lex;
	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 362 "latex.l"
{
		SetTexLval(yytext, NULL);
		return CMD_STACKREL_lex;
	}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 366 "latex.l"
{
		SetTexLval(yytext, NULL);
		return CHAR_AMPERSAND_lex;
	}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 370 "latex.l"
{
	SetTexLval(yytext, NULL);
	return CHAR_CARET_lex;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 374 "latex.l"
{
	const char *name;
	const char  *str;
	int        token;
	size_t         i;

	name = yytext + 1;

	str = LatexAtomic(name, &token);
	if( str != NULL )
	{	SetTexLval(yytext, str);
		return token;
	}
	for(i = 0; i < NDiacritical; i++)
	{	if( strcmp(Diacritical[i].name, name) == 0 )
		{	SetTexLval(yytext, Diacritical[i].mathml);
			return CMD_DIACRITICAL_lex;
		}
	}

	fataltex(
		yytext,
		" is not a valid command in OMhelp's Latex mode.",
		NULL
	);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 400 "latex.l"
{
	// ignore
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 403 "latex.l"
{
	SetTexLval("CHAR_ENDINPUT_lex", NULL);
	return CHAR_ENDINPUT_lex;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 407 "latex.l"
{
	SetTexLval(yytext, NULL);
	return CHAR_LEFTBRACE_lex;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 411 "latex.l"
{
	if( Cmd_Bracket_Mode == '[' )
	{	SetTexLval(yytext, NULL);
		Cmd_Bracket_Mode = ']';
		return CHAR_LEFTBRACKET_lex;
	}
	if( Cmd_Bracket_Mode == ']' ) fatalerr(
		"another '[' occurred while looking for the ']'\n",
		"that terminates a command argument started with a '['",
		NULL
	);
	SetTexLval(yytext, yytext);
	return CHAR_OPERATOR_lex;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 425 "latex.l"
{
	size_t i;

	i = strlen(yytext);
	assert( i > 0 );

	// check begins with a letter
	assert( isalpha( yytext[0] ) );

	SetTexLval(yytext, yytext);

	return CHAR_LETTERS_lex;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 438 "latex.l"
{
	// ignore
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 441 "latex.l"
{
	SetTexLval(yytext, yytext);
	return NUMBER_lex;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 445 "latex.l"
{	// operators that do not need conversion to Unicode

	SetTexLval(yytext, yytext);
	return CHAR_OPERATOR_lex;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 450 "latex.l"
{
	SetTexLval(yytext, NULL);
	return CHAR_RIGHTBRACE_lex;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 454 "latex.l"
{
	if( Cmd_Bracket_Mode == ']' )
	{	SetTexLval(yytext, NULL);
		Cmd_Bracket_Mode = '\0';
		return CHAR_RIGHTBRACKET_lex;
	}
	SetTexLval(yytext, yytext);
	return CHAR_OPERATOR_lex;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 463 "latex.l"
{
	SetTexLval(yytext, NULL);
	return CHAR_UNDERBAR_lex;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 467 "latex.l"
{
	// ignore
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 471 "latex.l"
{
	fataltex(
		"The character with ascii code ",
		int2str( (int) yytext[0] ),
		"\nis not a valid Latex input character.",
		NULL
	);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 480 "latex.l"
ECHO;
	YY_BREAK
#line 1412 "lex.tex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 2);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 165 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 2;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 165 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 164);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 480 "latex.l"

/****************************************************************************/

static char Token[MAX_TOKEN_NUMBER][MAX_TOKEN_LENGTH];
static int  TokenLine[MAX_TOKEN_NUMBER];
static int  TokenStart = 0;
static int  TokenNext  = 0;

static void SetTexLval(const char *token, const char *str)
{	int i;

	assert( token != NULL );

	if( DEBUG_TOKENS )
		printf("\nTexLex(%s) ", token);

	texlval.line  = LatexMacroInputLine();

	if( str == NULL )
		texlval.str = NULL;
	else	texlval.str = str_alloc(str);

	texlval.data  = 0;
	texlval.extra = NULL;
	texlval.next  = NULL;

	// copy the token into the next slot
	i = strlen(token);
	if( i >= MAX_TOKEN_LENGTH )
		i = MAX_TOKEN_LENGTH - 1;

	Token[TokenNext][i] = '\0';
	while( i > 0 )
	{	--i;
		Token[TokenNext][i] = token[i];
	}
	TokenLine[TokenNext] = LatexMacroInputLine();

	// increment the next and start pointers
	TokenNext = (TokenNext + 1) % MAX_TOKEN_NUMBER;
	if( TokenStart == TokenNext )
		TokenStart = (TokenStart + 1) % MAX_TOKEN_NUMBER;
	assert( TokenStart != TokenNext );


	if( Cmd_Bracket_Mode == '[' )
		Cmd_Bracket_Mode = '\0';

	return;

}

void LatexLexPut(int line, const char *input)
{
	LatexMacroUserInput(line, input);

	TokenStart  = 0;
	TokenNext   = 0;
	return;
}


int LatexLexHistory(int number, int length, int *line, char **token)
{	int ntoken;
	int i;
	int next;

	ntoken = 0;
	next   = TokenNext;
	while( next != TokenStart && ntoken < number )
	{	next--;
		if( next < 0 )
			next = MAX_TOKEN_NUMBER - 1;

		i = strlen(Token[next]);
		if( i >= length )
			i = length - 1;
		token[ntoken][i] = 0;
		while( i > 0 )
		{	--i;
			token[ntoken][i] = Token[next][i];
		}
		line[ntoken] = TokenLine[next];
		ntoken++;
	}
	return ntoken;
}
